version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build_test_lint:
    machine:
      image: 'ubuntu-2204:2022.10.2'

    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 18.15.0
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn --frozen-lockfile --network-timeout 180000
          name: Build app
      - run: sudo swapoff -a
      - run: sudo dd if=/dev/zero of=/swapfile bs=1G count=8
      - run: sudo chmod 0600 /swapfile
      - run: sudo mkswap /swapfile
      - run: sudo swapon /swapfile
      - run: grep Swap /proc/meminfo
      - run: sudo apt update
      - run:
          command: yarn run lint
          name: Lint app
      - run:
          command: yarn run bundle
          name: Bundle app
      - run:
          command: yarn run test
          name: Test app

workflows:
  build_test_lint:
    jobs:
      - build_test_lint
