---
version: 2.1

orbs:
  node: circleci/node@5.1.0

workflows:
  build_test_lint:
    jobs:
      - build_test_lint

jobs:
  build_test_lint:
    machine:
      image: 'ubuntu-2204:2022.10.2'

    steps:
      - checkout
      - node/install:
          install-yarn: true
          yarn-version: 1.22.19
          node-version: 19.0.0
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build app
          command: yarn --frozen-lockfile --network-timeout 180000
      - run:
          name: Lint app
          command: yarn run lint
      - run:
          name: Bundle app
          command: yarn run bundle
      - run:
          name: Log in to Docker Hub
          command: docker login --username ${DOCKER_HUB_USERNAME} --password ${DOCKER_HUB_CI_TOKEN}
      - run:
          name: Test app
          command: yarn run test
