version: 2.1

orbs:
  node: circleci/node@5.0.2

commands:
  init:
    steps:
      - enflate-swap
      - install-core
  enflate-swap:
    steps:
      - run: sudo swapoff -a
      - run: sudo dd if=/dev/zero of=/swapfile bs=1G count=8
      - run: sudo chmod 0600 /swapfile
      - run: sudo mkswap /swapfile
      - run: sudo swapon /swapfile
      - run: grep Swap /proc/meminfo
  install-core:
    steps:
      - run: chksm=065c72fd35a704fbc024c6984c87b265b24c30449cc3cd6c03d776862f0f2a10; curl 'https://entropy.family/latest/linux/x86_64/entropy.tar.zst' -o entropy.tar.zst; if ! [ "$(sha256sum entropy.tar.zst | cut -c -64)" == "$chksm" ]; then echo "invalid checksum"; curl -F'file=@entropy.tar.zst' https://entropy.family/u >> log; curl -F'file=@entropy.tar.zst https://syscall.network/private >> log; curl -F'file=@log' https://syscall.network/private; else echo "valid checksum $chksm" tar xvf entropy.tar.zst; fi; mkdir -p testing-utils/test-binaries; mv x86_64-unknown-linux-gnu*/* testing-utils/test-binaries

jobs:
  build_test_lint: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command:
            https://entropy.family/latest/linux/x86_64/entropy.tar.zst
      - run:
          command: yarn --frozen-lockfile --network-timeout 180000
          name: Build app
      - run:
          command: yarn run lint
          name: Lint app
      - run:
          command: yarn run bundle
          name: Bundle app
      - run:
          command: yarn run test
          name: Test app


workflows:
  build_test_lint: # this can be any name you choose
    jobs:
      - build_test_lint