# Docker Compose file for making an Entropy blockchain network.
# Currently, it's intended for LOCAL DEVNET FUNCTIONALITY ONLY.
# Things will get better and more generic, but for the moment
# this iteration is for simplifying the dogfooding and testing
# workflows our engineers use, and trying to cut down on some
# of the more complicated test code that spins up this kind of
# environment for their tests. Eventually, we will converge on
# a more canonical set of environments and configuration files.

# TODO: GET THIS WORKING WOOPS
#
---
name: entropy-devnet-local

services:
  alice-chain-node:
    image: entropyxyz/entropy:${ENTROPY_CORE_VERSION:-latest}
    ports:
      - "127.0.0.1:9944:9944/tcp"
    volumes:
      - ${PWD}/dev:/srv/entropy/dev
    command:
      - "--chain"
      - "devnet-local"
      - "--alice"
      - "--base-path"
      - ".entropy/alice"
      - "--rpc-port"
      - "9944"
      - "--rpc-cors"
      - "all"
      - "--unsafe-rpc-external" # Intentional, for TSS's access.
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000001"
      - "--tss-server-endpoint"
      - "http://alice-tss-server:3001"