name: GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
      - '!v*.*.*-*'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile # optional, --immutable
      - run: yarn generate:docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        # TODO: uncomment this before merge
        # if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
