name: CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: npm install -g yarn
        run: npm install -g yarn

      - name: yarn --frozen-lockfile --network-timeout 180000
        run: yarn --frozen-lockfile --network-timeout 180000

      - name: Run lint
        run: yarn run lint # will run `yarn install` command

      - name: Run bundle
        run: yarn run bundle # will run `yarn install` command
